# Generated by Django 3.2.6 on 2021-08-30 22:10

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='brukernavn')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='fornavn')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='etternavn')),
                ('nickname', models.CharField(max_length=150, null=True, unique=True, verbose_name='kallenavn')),
                ('gender', models.CharField(blank=True, choices=[(None, None), ('M', 'Mann'), ('F', 'Kvinne'), ('O', 'Annet')], default=None, max_length=1, null=True, verbose_name='kjønn')),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='mobilnummer')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='opprettet')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
