# Generated by Django 3.2.6 on 2021-09-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'bruker', 'verbose_name_plural': 'brukere'},
        ),
    ]
