# Generated by Django 3.2.5 on 2021-07-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sist redigert')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('name', models.CharField(max_length=200, verbose_name='navn')),
                ('name_latin', models.CharField(max_length=200, verbose_name='navn')),
                ('longevity', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('longevity_unit', models.CharField(blank=True, choices=[(None, ''), ('seconds', 'sekunder'), ('minutes', 'minutter'), ('hours', 'timer'), ('days', 'dager'), ('weeks', 'uker'), ('months', 'måneder'), ('years', 'år')], default=None, max_length=20, null=True, verbose_name='enhet')),
                ('water_freq', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('water_freq_unit', models.CharField(blank=True, choices=[(None, ''), ('seconds', 'sekunder'), ('minutes', 'minutter'), ('hours', 'timer'), ('days', 'dager'), ('weeks', 'uker'), ('months', 'måneder'), ('years', 'år')], default=None, max_length=20, null=True, verbose_name='enhet')),
                ('water_amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('water_amount_unit', models.CharField(blank=True, choices=[(None, ''), ('seconds', 'sekunder'), ('minutes', 'minutter'), ('hours', 'timer'), ('days', 'dager'), ('weeks', 'uker'), ('months', 'måneder'), ('years', 'år')], default=None, max_length=20, null=True, verbose_name='enhet')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_flower_set', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('last_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_flower_set', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av')),
                ('tags', models.ManyToManyField(to='root.Tag')),
            ],
            options={
                'verbose_name': 'blomst',
                'verbose_name_plural': 'blomster',
                'ordering': [],
            },
        ),
    ]
