# Generated by Django 3.2.5 on 2021-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='longevity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=100, verbose_name='levetid'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='water_amount',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=100, verbose_name='vannmengde'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='water_freq',
            field=models.DecimalField(decimal_places=1, default=7, max_digits=100, verbose_name='vannefrekvens'),
        ),
    ]
