# Generated by Django 3.2.6 on 2021-09-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='root.taggroup', verbose_name='tag-gruppe'),
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_groups', to='root.domain', verbose_name='tag-domene'),
        ),
    ]
