# Generated by Django 3.2.6 on 2021-08-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='group',
            new_name='tag_group',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'tag_group')},
        ),
    ]
